### ISSUE TITLE
NotImplementedError('Unknown decoder type: v1')

### ISSUE THREAD

**Issue by xiaofeifei-1** [LostXine/crossway_diffusion#6] opened 2024-08-04 09:10 UTC
**Hello, thank you for your a great work! I am following yours, now!
But, when I running your code, I have a error.**

**The repo`s code error link:**
https://github.com/LostXine/crossway_diffusion/blob/d53a4a30e88ab03f75ec4cc1a01b372bd744cd51/diffusion_policy/workspace/train_crossway_diffusion_unet_hybrid_workspace.py#L48C8-L48C91

**runing eval command:** `EGL_DEVICE_ID=0 python eval.py --checkpoint pretrained_models/checkpoints/crossway_diffusion-pusht-s43.ckpt  --output_dir pusht_eval_output`

**There is error:**
`Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/crossway_diff/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/xxx/Documents/Navigation/diff_policy/crossway_diffusion/diffusion_policy/policy/crossway_diffusion_unet_hybrid_image_policy.py", line 153, in __init__
    raise NotImplementedError(f'Unknown decoder type: {decode_ver}')
NotImplementedError: Unknown decoder type: v1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxx/Documents/Navigation/diff_policy/crossway_diffusion/eval.py", line 82, in <module>
    main()
  File "/home/xxx/anaconda3/envs/crossway_diff/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/crossway_diff/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/xxx/anaconda3/envs/crossway_diff/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/anaconda3/envs/crossway_diff/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/xxx/Documents/Navigation/diff_policy/crossway_diffusion/eval.py", line 51, in main
    workspace = cls(cfg, output_dir=output_dir)
  File "/home/xxx/Documents/Navigation/diff_policy/crossway_diffusion/diffusion_policy/workspace/train_crossway_diffusion_unet_hybrid_workspace.py", line 48, in __init__
    self.model: AEDiffusionUnetHybridImagePolicy = hydra.utils.instantiate(cfg.policy)
  File "/home/xxx/anaconda3/envs/crossway_diff/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 222, in instantiate
    return instantiate_node(
  File "/home/xxx/anaconda3/envs/crossway_diff/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 339, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/home/xxx/anaconda3/envs/crossway_diff/lib/python3.9/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'diffusion_policy.policy.crossway_diffusion_unet_hybrid_image_policy.AEDiffusionUnetHybridImagePolicy':
NotImplementedError('Unknown decoder type: v1')
full_key: policy`

**So, what can I do to solve it! 
Thank you!**

**Comment by xiaofeifei-1** [comment] 2024-08-04 09:24
I download your pretrained models and evaluation results  at [Hugging Face](https://huggingface.co/varunbel/crossway_diffusion).

When running eval code, the error happened, resulting from "decode_ver == 'v1' "!

**Comment by LostXine** [comment] 2024-08-04 09:27
Hi @xiaofeifei-1 

Thanks for your interest in our work. 
This is caused by a recent update which makes the old checkpoints incompatible.
I've updated the code and you can give it a try again.

Thanks,

**Comment by xiaofeifei-1** [comment] 2024-08-04 09:30
> Hi @xiaofeifei-1
> 
> Thanks for your interest in our work. This is caused by a recent update which makes the old checkpoints incompatible. I've updated the code and you can give it a try again.
> 
> Thanks,

Thank you for your prompt reply. I am very grateful.

**Comment by LostXine** [comment] 2024-08-05 03:02
Hi @xiaofeifei-1 

I'll close this issue for now as I assume it works. Please feel free to reopen it if needed.

Best,

**Closed as completed by LostXine** 2024-08-05 03:02 UTC
